- project:
    templates:
      - sf-ci-python-jobs
      - sf-ci-jobs
      - sf-ci-packages-publish
    check:
      jobs:
        - tox-py27:
            voting: false
        - tox-py36:
            nodeset: fedora-latest-runc
            voting: true
        - tox-pep8-py36:
            nodeset: fedora-latest-runc
            voting: true
        - sf-rpm-build:
            required-projects:
              - software-factory/cauth-distgit
    gate:
      jobs:
        - tox-py27:
            voting: false
        - tox-py36:
            nodeset: fedora-latest-runc
            voting: true
        - tox-pep8-py36:
            nodeset: fedora-latest-runc
            voting: true
        - sf-rpm-build:
            required-projects:
              - software-factory/cauth-distgit
    release:
      jobs:
        - sf-rpm-publish:
            required-projects:
              - software-factory/cauth-distgit
