- project:
    templates:
      - sf-ci-jobs
      - sf-ci-packages-publish
    check:
      jobs:
        - tox-py36:
            vars:
              tox_install_siblings: false
            nodeset:
              nodes:
                - name: centos-8
                  label: pod-centos-8
        - tox-pep8:
            nodeset:
              nodes:
                - name: centos-8
                  label: pod-centos-8
    gate:
      queue: sf
      jobs:
        - tox-py36:
            vars:
              tox_install_siblings: false
            nodeset:
              nodes:
                - name: centos-8
                  label: pod-centos-8
        - tox-pep8:
            nodeset:
              nodes:
                - name: centos-8
                  label: pod-centos-8
